"""Cycle 3 event rules — aligned with doc/周期3-任务拆分.md."""

YEAR_GAME_DAYS = 365

SOCIAL_PERIOD_GAME_DAYS = 10
SOCIAL_SPAN_GAME_DAYS = 2

SOCIAL_FEED_TARGET = 10
BIRTHDAY_CUDDLE_TARGET = 3
DAILY_PAT_TARGET = 5

SOCIAL_REWARD_COINS = 50
BIRTHDAY_REWARD_COINS = 30
DAILY_REWARD_COINS = 20

TEMPLATE_BIRTHDAY_V1 = "birthday_v1"
TEMPLATE_SOCIAL_V1 = "garden_social_v1"
TEMPLATE_DAILY_V1 = "daily_pat_v1"
